tokenizer_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.35k/2.35k [00:00<00:00, 2.49MB/s]
C:\Users\a.frost\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\file_download.py:140: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\a.frost\.cache\huggingface\hub\models--google--switch-base-8. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
spiece.model: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 792k/792k [00:00<00:00, 7.55MB/s]
tokenizer.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.42M/2.42M [00:00<00:00, 4.69MB/s]
special_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.20k/2.20k [00:00<00:00, 619kB/s]
README.md: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.24k/6.24k [00:00<00:00, 1.85MB/s]
C:\Users\a.frost\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\file_download.py:140: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\a.frost\.cache\huggingface\hub\datasets--xsum. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
xsum.py: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.76k/5.76k [00:00<00:00, 2.56MB/s]
Traceback (most recent call last):
  File "c:\Users\a.frost\Desktop\py\Pytorch training\pytorch-tutorial\traingsdaten.py", line 196, in <module>
    trained_model, tokenizer = main()
                               ^^^^^^
  File "c:\Users\a.frost\Desktop\py\Pytorch training\pytorch-tutorial\traingsdaten.py", line 134, in main
    dataset = load_dataset("xsum")
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a.frost\AppData\Local\Programs\Python\Python311\Lib\site-packages\datasets\load.py", line 2129, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a.frost\AppData\Local\Programs\Python\Python311\Lib\site-packages\datasets\load.py", line 1849, in load_dataset_builder
    dataset_module = dataset_module_factory(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a.frost\AppData\Local\Programs\Python\Python311\Lib\site-packages\datasets\load.py", line 1731, in dataset_module_factory
    raise e1 from None
  File "C:\Users\a.frost\AppData\Local\Programs\Python\Python311\Lib\site-packages\datasets\load.py", line 1681, in dataset_module_factory
    ).get_module()
      ^^^^^^^^^^^^
  File "C:\Users\a.frost\AppData\Local\Programs\Python\Python311\Lib\site-packages\datasets\load.py", line 1331, in get_module
    trust_remote_code = resolve_trust_remote_code(self.trust_remote_code, self.name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a.frost\AppData\Local\Programs\Python\Python311\Lib\site-packages\datasets\load.py", line 138, in resolve_trust_remote_code
    raise ValueError(
ValueError: The repository for xsum contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/xsum.
Please pass the argument `trust_remote_code=True` to allow custom code to be run.
